### ISSUE TITLE
Test is sensitive to RNG

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/LighthouseFlux.jl#33]
https://github.com/beacon-biosignals/LighthouseFlux.jl/blob/e58e900768d244e39cc43e5309891585956cd81d/test/runtests.jl#L50-L52

is failing. I think we should try to scrap it and come up with a more robust test, since I remember this being an issue in the past too.

xref https://github.com/beacon-biosignals/LighthouseFlux.jl/pull/32

**Comment by hannahilea** [comment]
>  I think we should try to scrap it and come up with a more robust test, since I remember this being an issue in the past too.

Agreed! Although I _am_ confused that this is a problem at all, seeing as we're using StableRNGs here everywhere I'd expect it to matter (without having poked around any deeper).

**Comment by hannahilea** [comment]
FINALLY. 🏆
